spring:
  kafka:
    consumer:

      #unkonwledge: lo q hace es comprobar q lops mensajes se entregan correctamete

      #servidor bootstrap

      bootstrap_servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: 1
      auto_offset_reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #paquetes confiables para kafka
      properties:
        spring.json.trusted.packages: com.kafka.consumer
server:
  port : 8070
