spring:
  kafka:
    producer:
      #unkonwledge: lo q hace es comprobar q lops mensajes se entregan correctamete
      acks: -1
      #servidor bootstrap

      bootstrap_servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



